[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
collateral_token_faucet = "DDFXv1hETR8pQSpNbzCxTX7jm1Hr57V4oihDGosXQfgC"
range_bet_program = "97i8BgDJG6yZggN2Di5UnERs6X5PqYqnkSvkMdvw1d5J"

[programs.localnet]
collateral_token_faucet = "DDFXv1hETR8pQSpNbzCxTX7jm1Hr57V4oihDGosXQfgC"
range_bet_program = "97i8BgDJG6yZggN2Di5UnERs6X5PqYqnkSvkMdvw1d5J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/range-bet-program", "programs/collateral_token_faucet"]

[scripts]
account-fetch = "node scripts/fetch-accounts.js"
buy-tokens = "node scripts/buy-tokens.js"
close-market = "node scripts/close-market.js"
init-market = "node scripts/init-market.js"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
