[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
signals_breakout_contracts = "97i8BgDJG6yZggN2Di5UnERs6X5PqYqnkSvkMdvw1d5J"

[programs.devnet]
signals_breakout_contracts = "97i8BgDJG6yZggN2Di5UnERs6X5PqYqnkSvkMdvw1d5J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
account-fetch = "node scripts/fetch-accounts.js"
init-market = "node scripts/init-market.js"
buy-tokens = "node scripts/buy-tokens.js"
close-market = "node scripts/close-market.js"

[workspace]
name = "signals-breakout-contracts"
