[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
range_bet_program = "97i8BgDJG6yZggN2Di5UnERs6X5PqYqnkSvkMdvw1d5J"

[programs.devnet]
range_bet_program = "97i8BgDJG6yZggN2Di5UnERs6X5PqYqnkSvkMdvw1d5J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/whworjs/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
account-fetch = "node scripts/fetch-accounts.js"
init-market = "node scripts/init-market.js"
buy-tokens = "node scripts/buy-tokens.js"
close-market = "node scripts/close-market.js"

[package]
name = "signals-breakout-contracts"
version = "0.1.0"
description = "Signals Breakout Contracts"
homepage = "https://github.com/signals-protocol/signals-breakout-contracts"
repository = "https://github.com/signals-protocol/signals-breakout-contracts"
authors = ["Signals Team"]
license = "Apache-2.0"

[workspace]
name = "signals-breakout-contracts"
members = [
    "programs/range-bet-program"
]
